version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing app dependencies...
      - yarn install
  build:
    commands:
      - echo Building static site...
        - yarn build
        - echo Run tests...
        - CI=true yarn test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  paths:
    - './build/**/*'

cache:
  paths:
    - './node_modules/**/*'